version: '3'

services:
  web1:
    build: ./flask
    ports:
      - "8080:8080"
    environment:
      DB_URI: ${DB_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION_NAME: ${S3_REGION_NAME}
      FIREBASE_BUCKET_ADDRESS: ${FIREBASE_BUCKET_ADDRESS}
      ML_SERVER_BASER_URL: ${ML_SERVER_BASER_URL}
      SERVICE_ACCOUNT_KEY: ${SERVICE_ACCOUNT_KEY}

  web2:
    build: ./flask
    ports:
      - "8081:8080"
    environment:
      DB_URI: ${DB_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION_NAME: ${S3_REGION_NAME}
      FIREBASE_BUCKET_ADDRESS: ${FIREBASE_BUCKET_ADDRESS}
      ML_SERVER_BASER_URL: ${ML_SERVER_BASER_URL}
      SERVICE_ACCOUNT_KEY: ${SERVICE_ACCOUNT_KEY}

  web3:
    build: ./flask
    ports:
      - "8082:8080"
    environment:
      DB_URI: ${DB_URI}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION_NAME: ${S3_REGION_NAME}
      FIREBASE_BUCKET_ADDRESS: ${FIREBASE_BUCKET_ADDRESS}
      ML_SERVER_BASER_URL: ${ML_SERVER_BASER_URL}
      SERVICE_ACCOUNT_KEY: ${SERVICE_ACCOUNT_KEY}

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
      - web3


