name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Prepare serviceAccountKey and .env
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > ./flask/serviceAccountKey.json
          echo "DB_URI=${{ secrets.DOT_ENV }}" > ./flask/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker images
        run: docker-compose build

      - name: Push the Docker images
        run: docker-compose push

  deploy:
    needs: build-and-push # This ensures deployment starts after the build-and-push job is completed
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y openssh-client

          # Start SSH agent
          eval $(ssh-agent -s)

          # Create the .ssh directory and config file
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

          # Set permissions for the config file
          chmod 644 ~/.ssh/config

          # Add SSH key stored in GitHub secrets to the agent store
          echo "$KEY" > temp_key
          chmod 600 temp_key
          ssh-add temp_key
          rm temp_key

          # SSH to the EC2 instance and execute commands
          ssh -o 'StrictHostKeyChecking=no' $USERNAME@$HOST << 'ENDSSH'

          # 여기에 서버에서 실행할 명령들 추가
          
          # EC2 인스턴스에서 필요한 명령 실행
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          cd DP_Backend
          docker-compose pull
          docker-compose up -d
          ENDSSH



          